// <auto-generated />
namespace _2010107281_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Turismo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Turismo));
        
        string IMigrationMetadata.Id
        {
            get { return "201706101710599_Turismo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
